print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("Multiplication of these two numbers are", int(s1) ** int(s2))
print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("The answer is", int(s1) == int(s2))
print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("sum of these two numbers are", int(s1) + int(s2))
print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("The answer is", int(s1) // int(s2))
print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("The answer is", int(s1) * int(s2))
print("Enter first number")
s1 = input()
print("Enter Second number")
s2 = input()
print("The answer is", int(s1) % int(s2))
